-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. USERS
-- Linked to the auth.users table if using Supabase Auth, or standalone for Web3
create table public.users (
  id uuid primary key default uuid_generate_v4(),
  wallet_address text unique not null,
  username text,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. MARKETS
-- The core prediction markets
create table public.markets (
  id uuid primary key default uuid_generate_v4(),
  condition_id text unique not null, -- On-chain ID
  question text not null,
  description text,
  category text not null, -- 'Politics', 'Sports', 'Crypto', 'Pop Culture'
  outcome_tokens text[] not null, -- ['Yes', 'No']
  image_url text,
  end_date timestamp with time zone not null,
  status text default 'OPEN' check (status in ('OPEN', 'Review', 'RESOLVED')),
  
  -- Stats (Derived/Cached for performance)
  total_volume_usdc numeric default 0,
  created_by uuid references public.users(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. OUTCOMES
-- Specific outcomes for a market (e.g., "Yes" or "No")
create table public.outcomes (
  id bigint generated by default as identity primary key,
  market_id uuid references public.markets(id) on delete cascade not null,
  name text not null, -- "Yes"
  index integer not null, -- 0
  initial_probability numeric default 0.5,
  current_probability numeric default 0.5, -- e.g., 0.75
  price numeric default 0.5 -- Latest price (approx same as probability)
);

-- 4. MARKET_PRICES (History)
-- For charting price history over time
create table public.market_prices (
  id bigint generated by default as identity primary key,
  market_id uuid references public.markets(id) on delete cascade not null,
  outcome_index integer not null,
  price numeric not null,
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. TRADES (Activity)
-- Mirror of on-chain trades for "Activity" feed
create table public.trades (
  id uuid primary key default uuid_generate_v4(),
  market_id uuid references public.markets(id) not null,
  user_id uuid references public.users(id),
  outcome_index integer not null,
  is_buy boolean not null, -- true = Buy, false = Sell
  share_amount numeric not null,
  usdc_amount numeric not null,
  tx_hash text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS (Row Level Security) Policies
-- Enable RLS
alter table public.users enable row level security;
alter table public.markets enable row level security;
alter table public.outcomes enable row level security;
alter table public.market_prices enable row level security;
alter table public.trades enable row level security;

-- Policies: Everyone can read everything (Public Data)
create policy "Public read access for users" on public.users for select using (true);
create policy "Public read access for markets" on public.markets for select using (true);
create policy "Public read access for outcomes" on public.outcomes for select using (true);
create policy "Public read access for market_prices" on public.market_prices for select using (true);
create policy "Public read access for trades" on public.trades for select using (true);

-- Functions
-- Function to automatically update timestamps if needed (omitted for MVP simplicity)
