/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IConditionalTokensInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getCollectionId"
      | "getPositionId"
      | "mergePositions"
      | "splitPosition"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getCollectionId",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPositionId",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mergePositions",
    values: [AddressLike, BytesLike, BytesLike, BigNumberish[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "splitPosition",
    values: [AddressLike, BytesLike, BytesLike, BigNumberish[], BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getCollectionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPositionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mergePositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "splitPosition",
    data: BytesLike
  ): Result;
}

export interface IConditionalTokens extends BaseContract {
  connect(runner?: ContractRunner | null): IConditionalTokens;
  waitForDeployment(): Promise<this>;

  interface: IConditionalTokensInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getCollectionId: TypedContractMethod<
    [
      parentCollectionId: BytesLike,
      conditionId: BytesLike,
      indexSet: BigNumberish
    ],
    [string],
    "view"
  >;

  getPositionId: TypedContractMethod<
    [collateralToken: AddressLike, collectionId: BytesLike],
    [bigint],
    "view"
  >;

  mergePositions: TypedContractMethod<
    [
      collateralToken: AddressLike,
      parentCollectionId: BytesLike,
      conditionId: BytesLike,
      partition: BigNumberish[],
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  splitPosition: TypedContractMethod<
    [
      collateralToken: AddressLike,
      parentCollectionId: BytesLike,
      conditionId: BytesLike,
      partition: BigNumberish[],
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getCollectionId"
  ): TypedContractMethod<
    [
      parentCollectionId: BytesLike,
      conditionId: BytesLike,
      indexSet: BigNumberish
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPositionId"
  ): TypedContractMethod<
    [collateralToken: AddressLike, collectionId: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "mergePositions"
  ): TypedContractMethod<
    [
      collateralToken: AddressLike,
      parentCollectionId: BytesLike,
      conditionId: BytesLike,
      partition: BigNumberish[],
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "splitPosition"
  ): TypedContractMethod<
    [
      collateralToken: AddressLike,
      parentCollectionId: BytesLike,
      conditionId: BytesLike,
      partition: BigNumberish[],
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
